version: '2'
services:
    web:
        image: jmutai/alpine-caddy
        ports:
            -   80:80
        volumes:
            -   ./Caddyfile:/etc/Caddyfile
            -   ./public:/var/www/html
            -   ./.caddy:/root/.caddy
