# docker-compose up -d
 version: '2'
 services:
   db:
     image: mariadb
     container_name: mariadb-kipepeo
     volumes:
       - "~/.wp/db:/var/lib/mysql"
     restart: on-failure 
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp-kipepeo
     volumes:
       - "~/.wp/html:/var/www/html"  
       - "./phpinfo.php:/var/www/html/phpinfo.php"
       - "./php.ini:/usr/local/etc/php/php.ini"
       - "./default-constants.php:/var/www/html/wp-includes/default-constants.php"
     links:
       - db
     ports:
       - "80:80"
     restart: on-failure 
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
